apiVersion: v1
kind: Service
metadata:
  name: OrderAndPayment
spec:
  selector:
    app: OrderAndPayment
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
